### ISSUE TITLE
Panic on fx.App.Done

### ISSUE THREAD

**Issue by aguber2** [uber-go/fx#669] opened 2019-02-10 19:05 UTC
Appears to be caused by this commit: https://github.com/uber-go/fx/commit/5f6023c227a75fe5a8349df73f42ec2c507a08b6

`donesMu` was added to the `App` struct but never initialized so when `Done` is called we get a panic trying to take the lock

**Comment by akshayjshah** [comment] 2019-02-11 04:27
Can you post a reproduction of the issue? The zero value of `sync.RWMutex` is an unlocked mutex, so there's no need to initialize it explicitly. See https://play.golang.org/p/0fpsW88YuhS for an example.

**Comment by glibsm** [comment] 2019-04-19 21:48
Going to optimistically close this issue assuming that it's resolved since there hasn't been any activity for a long time. Please re-open if you get a repro case.

**Closed by glibsm** 2019-04-19 21:48 UTC
Labels: bug
