### ISSUE TITLE
Unable to terminate cleanly on Windows/mingw64

### ISSUE THREAD

**Issue by oakad** [uber-go/fx#819] opened 2021-11-30 09:25 UTC
mingw64 go 1.17/fx 1.15.0

When running an fx enabled server on Windows, attempt to terminate it in console with Ctrl-C causes it to die on the spot, OnStop hooks not called. Programmatic signals like when using `winpty` are not any better.

I had not used Windows/mingw64 in years, but I do recollect that this feature used to work ok.

I have tried mintty vs powershell, and all the other usual tricks.

**Comment by sywhang** [comment] 2021-11-30 09:55
Thanks for reporting this issue. Have you tried running against the master branch? This issue seems like a duplicate of https://github.com/uber-go/fx/issues/781 which has been fixed by #812 recently. We will be doing a release that will include this fix this week. 

If the issue seems to still exist in master branch, feel free to reopen the issue.

**Closed by sywhang** 2021-11-30 09:55 UTC
