### ISSUE TITLE
Invokes are tied to lifecycle

### ISSUE THREAD

**Issue by bayesianmind** [uber-go/fx#550] opened 2017-07-02 19:28 UTC
## Problem: 
Fx Invokes don't happen until Start() is called and thus are tied to lifecycle.

## Background
There is not an opportunity for the service author to interact with the fully resolved graph until all the `Start()` hooks have been executed.

##  Possible fix
Run Invokes at fx.New() time rather than at fx.Start().

This seems like the simplest solution. The only downside I see is if users are misusing the system and putting code that should be in a lifecycle event into their invokes than that code would be run at New() time which doesn't have timeouts.

**Comment by glibsm** [comment] 2017-07-02 23:55
Thanks for filing the issue.

I'm not sure that I agree with the initial statement - that `Invoke` on startup is a problem. `Invoke` on startup is actually "working as designed", since that's how we boot up the app.

I'm not sure I understand how Option A would work. If `Invokes` are not run specifically on the App startup, then you don't give a chance for the graph to properly form before starting to resolve it. Similar things applies to the hooks as well - hooks are only executed for the items that were resolved, therefore will be part of this application's runtime.

It's very difficult for me to reason about the options, because I don't fully understand what the problem is and I suggest that we spend some time at the whiteboard after the break.

**Comment by akshayjshah** [comment] 2017-07-03 23:33
@bayesianmind Can you (perhaps in an internal task or email) point out some concrete places where you're implementing this generate-on-compile functionality? In general, this seems odd to me - I'm not fully understanding why the generation and build steps aren't completely separate, like `go generate` and `go build`.

**Comment by glibsm** [comment] 2017-07-05 23:43
I had a chance to sync with @bayesianmind and talk through the problem at hand. 

It essentially boils down the to the invokes running as part of app start, rather than at app init. I will open a PR so we can use that in combination with this issue for discussion.

**Comment by breerly** [comment] 2017-07-11 23:41
@bayesianmind can you describe the specific usecase here again?

**Comment by bayesianmind** [comment] 2017-07-11 23:59
Sure!
Two main things:
1) We want to make sure the user's types/invokes can resolved ASAP before lifecycle starts going off and doing things
2) Catalyst runs some of the invokes outside of the main runtime in order to know which handlers are registered so we can do extra handler-specific code-gen. For that case we want to run all the provides and invokes but not trigger lifecycle events (since we're not really starting the worker, we're just grabbing some info)

**Comment by breerly** [comment] 2017-07-12 02:49
I think #1 is a non-issue since Start will err on invoke and not run lifecycle, although I do see merit in pulling this as early as possible.

#2 makes a ton of sense - I'm on board!

**Comment by breerly** [comment] 2017-07-13 00:31
Looks like @glibsm's PR #551 is ready for review!

**Closed** 2017-07-18 17:54 UTC
Labels: discussion
