### ISSUE TITLE
config - Deep merge semantics?

### ISSUE THREAD

**Issue by breerly** [uber-go/fx#213] opened 2017-02-03 00:01 UTC
I don't see any docs or tests that describe how deep merge semantics work - are maps and objects merged, or is this just top-level? 

https://github.com/uber-go/fx/tree/master/config

**Comment by dmcaulay** [comment] 2017-02-03 00:12
I have noticed an issue during my development. Here's the the example yaml:

```
# config/base.yaml

modules:
  rpc:
    name: mormont
    tchannel:
      listenOn: localhost
      advertise: true
      peerList: /etc/uber/hyperbahn/hosts.json
    inbounds:
      - tchannel:
          port: ${UBER_PORT_TCHANNEL:0}
    outbounds:
      - service: rosetta
        http:
          host: localhost
          port: 14797
          path: /thrift
      - services:
          - populous
          - safari
          - treatment
          - trident
        tchannel:
          host: 127.0.0.1
          port: ${UBER_PORT_TCHANNEL:0}
```

```
# config/development.yaml
modules:
  rpc:
    name: mormont
    tchannel:
      listenOn: localhost
      advertise: false
    inbounds:
      - tchannel:
          port: ${UBER_PORT_TCHANNEL:0}
    outbounds:
      - service: rosetta
        http:
          host: localhost
          port: 14797
          path: /thrift
      - services:
          - populous
          - safari
          - treatment
          - trident
        tchannel:
          host: 127.0.0.1
          port: ${UBER_PORT_TCHANNEL:0}
```

The issue that I'm seeing is that `advertise` is still `false` when I run in development. Other keys are updated properly:

```
# config/base.yaml

uconfig:
  enabled: true
```

```
# config/development.yaml

uconfig:
  enabled: true
  UConfigDir: mormont-config/crc_configs
```

I haven't had time to dig in and determine the root cause.

**Comment by alsamylkin** [comment] 2017-02-03 00:14
Isn't  advertise: false in the development.yaml?

**Comment by glibsm** [comment] 2017-02-03 00:15
Thanks for reporting this, guys.
I believe our intention is to deep merge, otherwise having base.yaml becomes pointless really quick.

@alsamylkin it's false in development, but I think what Dan is saying is having loaded development.yaml config still returns true for that key.

**Comment by alsamylkin** [comment] 2017-02-03 00:28
Merging works only for yaml provider and should be the same as you'll Unmarshal two configs to the same variable.

**Comment by dmcaulay** [comment] 2017-02-03 21:24
The config issue that I was seeing was on my side. Thanks for the help @alsamylkin.

Do we still need to add docs?

**Comment by alsamylkin** [comment] 2017-02-03 21:51
Yep, created ticket to track GFM-340

**Comment by dmcaulay** [comment] 2017-02-07 20:52
i'm not sure what the protocol is. should we close this and track in jira or keep both issues open?

**Comment by sectioneight** [comment] 2017-02-07 20:54
Moving to JIRA

**Closed by sectioneight** 2017-02-07 20:54 UTC
